import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Brand & Header
    'brand.subtitle': 'Quantic Social media & videos',
    'search.placeholder': 'Buscar videos, fotos, gifs, posts de texto...',
    'search.voice': 'Búsqueda por voz con IA',
    'search.clear': 'Limpiar',
    'nav.publish': 'PUBLICAR',
    'nav.director': 'Director IA',
    'nav.directorFull': 'Director Creativo IA',
    'nav.studio': 'ESTUDIO',
    'nav.channel': 'CANAL',
    'nav.channelTooltip': 'Crear o gestionar tu canal',
    'nav.signIn': 'Ingresar',
    'nav.signUp': 'Registro',
    'nav.myProfile': 'Mi Perfil y Canal',
    'nav.publishMedia': 'Publicar Video / Foto / GIF',
    'nav.signOut': 'Cerrar Sesión',
    'nav.publishTooltip': 'Publicar y Compartir (Videos, Shorts, Fotos, Textos, GIFs)',
    'nav.langSwitch': 'Switch to English',
    'nav.langLabel': 'Idioma: Español',
    'nav.howToUse': '¿Cómo Usar?',
    'nav.policies': 'Políticas',
    'nav.about': 'Sobre Nosotros',
    
    // Tabs
    'tab.feed': 'Videos Largos (16:9)',
    'tab.shorts': 'Shorts (9:16)',
    'tab.photos': 'Fotos & Arte',
    'tab.posts': 'Comunidad',
    'tab.gifs': 'Hub de GIFs',
    'tab.book': '3D Book-Flip',
    'tab.quad': 'Quad-View',
    'tab.live': 'Omni-Live',
    'tab.dms': 'Mensajes DM',
    'tab.moderation': 'Moderación IA',

    // How to Use Modal
    'help.title': 'GUÍA INTERACTIVA & CÓMO USAR',
    'help.subtitle': 'Aprende a dominar todas las innovaciones táctiles, 3D, físicas y herramientas de IA',
    'help.clothTitle': '1. Física de Pañuelo 3D Orgánico (Videos Largos y Shorts)',
    'help.clothDesc': 'Nuestra tecnología de tela de seda 3D te permite interactuar con cualquier video como si fuera un pañuelo físico:',
    'help.flingUp': 'Jalar Arriba = Siguiente',
    'help.flingUpDesc': 'Al arrastrar el video hacia el tope superior y soltarlo, saldrá volando en 3D hacia el cosmos y se cargará el Siguiente Video.',
    'help.flingDown': 'Jalar Abajo = Anterior',
    'help.flingDownDesc': 'Al arrastrar el video hacia el tope inferior, se proyectará hacia abajo y restaurará el Video Anterior de la lista.',
    'help.freeRoam': 'Paseo Libre y Rebote',
    'help.freeRoamDesc': 'Puedes pasear el video por cualquier punto de la pantalla completa. Si lo sueltas en el medio, rebotará elásticamente a su marco original.',
    'help.dragThumbTitle': '2. Arrastrar Miniaturas hacia la Derecha sobre el Reproductor',
    'help.dragThumbDesc': 'En la lista de videos largos, puedes pulsar cualquier miniatura y jalarla con el cursor o el dedo hacia la derecha. Al soltarla encima del reproductor principal, se convertirá instantáneamente en el nuevo video activo en reproducción.',
    'help.authTitle': '3. Suscripciones, Cuenta de Creador y Publicación Real en la Nube',
    'help.authDesc': 'Con la integración de Firebase y Google Sign-In, puedes registrar tu propio canal en 1 clic. Podrás publicar videos largos en 16:9, Shorts en 9:16, fotografías en ultra definición, posts de texto, notas de voz holográficas y GIFs animados que se guardan en la nube permanentemente.',
    'help.liveTitle': 'Videollamadas 4K & Omni-Live',
    'help.liveDesc': 'Inicia llamadas de video directas P2P de alta fidelidad desde el panel de usuarios conectados, o transmite en Omni-Live con soporte para cámara dual e invitados en el escenario.',
    'help.aiTitle': 'Director Creativo & Quantum AI',
    'help.aiDesc': 'Utiliza la suite de IA impulsada por Gemini para generar ideas virales, guiones, sintetizar música procedural con Lyria y animar fotos a video con Veo 3.1.',
    'help.gotIt': '¡ENTENDIDO!',

    // Policies Modal
    'policies.title': 'POLÍTICAS DE PRIVACIDAD & TÉRMINOS',
    'policies.subtitle': 'Compromiso de protección de datos, seguridad en la nube y derechos del creador',
    'policies.sec1Title': '1. Protección de Datos y Almacenamiento Cifrado',
    'policies.sec1Desc': 'En QuanticTube protegemos tu información personal con los más altos estándares criptográficos de la industria. Tus credenciales de acceso se gestionan mediante Firebase Authentication y Google Cloud Firestore, asegurando que tus contraseñas y datos nunca sean expuestos a intermediarios.',
    'policies.sec2Title': '2. Propiedad Intelectual del Creador y Cero Venta de Datos',
    'policies.sec2Desc': 'Tú conservas el 100% de los derechos de autor de todo el contenido que publiques (videos, fotos, música, podcasts y GIFs). QuanticTube NUNCA vende ni comercializa tu información personal o hábitos de navegación a empresas de publicidad de terceros.',
    'policies.sec3Title': '3. Moderación Automatizada con IA & Normas de Convivencia',
    'policies.sec3Desc': 'Contamos con un sistema inteligente de escaneo en tiempo real con Gemini AI para prevenir el acoso, discurso de odio, spam y contenido perjudicial. Los comentarios tóxicos son neutralizados y desintegrados de inmediato para proteger a nuestra comunidad de creadores.',
    'policies.sec4Title': '4. Uso de Cookies & Almacenamiento Local',
    'policies.sec4Desc': 'Utilizamos almacenamiento local y cookies técnicas estrictamente necesarias para recordar tus preferencias de idioma, modo de audio espacial y sesión activa.',
    'policies.accept': 'ACEPTAR Y CONTINUAR',

    // About Us Modal
    'about.title': 'SOBRE',
    'about.subtitle': 'La plataforma social multimedia y de video del futuro',
    'about.missionTitle': 'Nuestra Misión: Superar los Límites del Video y las Redes Sociales',
    'about.missionDesc': 'QuanticTube nace con la visión de revolucionar la forma en que el mundo consume, crea y comparte contenido. Reuniendo lo mejor de YouTube (videos largos 16:9), TikTok (Shorts verticales interactivos 9:16), Instagram (galerías de fotografía y arte digital), X (microblogging y notas de voz), y Twitch (estudio en vivo Omni-Live con WebRTC), todo potenciado por física de pañuelo 3D orgánico y control automatizado con Inteligencia Artificial.',
    'about.techPillar': 'Poder Tecnológico Cuántico',
    'about.techDesc': 'Desarrollado con React 19, TypeScript, aceleración 3D por GPU (WebGL/CSS 3D Transforms), WebRTC de latencia ultra baja y Web Audio API procedural.',
    'about.aiPillar': 'Inteligencia Artificial Gemini 3.8',
    'about.aiDesc': 'Asistencia inteligente en tiempo real, director creativo de guiones, generador de video Veo 3.1, moderación automática y síntesis musical Lyria.',
    'about.founder': 'Creado & Diseñado por Memo Lopez',
    'about.creatorBadge': 'Fundador & Arquitecto',
    'about.founderNote': 'Una plataforma concebida desde el corazón para conectar creadores globales con una experiencia visual y táctil sin precedentes.',
    'about.close': 'CERRAR',

    // Long Videos View
    'long.title': 'VIDEOS LARGOS',
    'long.sub': '16:9 & CINE',
    'long.desc': 'Transmisiones 4K, conciertos holográficos y producciones cinematográficas',
    'long.publishBtn': 'Publicar Video Largo',
    'long.searchPlaceholder': 'Buscar en Videos Largos (ej. Mariachi, Zócalo, Synthwave, 4K)...',
    'long.tagAll': '🔥 Todos 16:9',
    'long.tagAi': '⚡ IA Veo 3.1',
    'long.tagCyber': '🌆 Cyberpunk',
    'long.tagSynth': '🎹 Synthwave',
    'long.playlistTitle': 'PLAYLIST DE VIDEOS LARGOS',
    'long.followers': 'seguidores cuánticos',
    'long.none': 'No hay videos seleccionados',

    // Hero Video Player
    'player.views': 'vistas',
    'player.likes': 'Me gusta',
    'player.comments': 'Comentarios',
    'player.share': 'Compartir',
    'player.draw': 'Dibujar',
    'player.drawTooltip': 'Lienzo de dibujo en vivo',
    'player.pin': 'Fijar Pin',
    'player.pinTooltip': 'Fijar comentario espacial en X,Y',
    'player.subtitles': 'Subtítulos e IA',
    'player.snapshot': '4K Snapshot',
    'player.snapshotTooltip': 'Captura de fotograma 4K',
    'player.clearDrawing': 'Limpiar trazos',
    'player.pinModalTitle': 'Pin en',
    'player.pinPlaceholder': 'Escribe tu comentario espacial...',
    'player.cancel': 'Cancelar',
    'player.savePin': 'Fijar Pin',
    'player.subtitlesTitle': 'Subtítulos IA',
    'player.reactionHeart': 'Corazón Neón',
    'player.reactionFire': 'Fuego Azteca',
    'player.reactionTaco': 'Taco Neón',
    'player.reactionSkull': 'Calavera Cyber',
    'player.reactionRose': 'Rosa Neón',

    // Shorts View
    'shorts.title': 'VIDEOS CORTOS',
    'shorts.sub': 'SHORTS 9:16 EN 3D',
    'shorts.desc': 'Física de pañuelo 3D orgánico, alta nitidez, colores vivos y audio espacial',
    'shorts.publishBtn': 'Publicar Short 9:16',
    'shorts.searchPlaceholder': 'Buscar en Shorts 9:16 (ej. Mariachi, IA, Viral, Baile, Beat)...',
    'shorts.badge': 'SHORT 3D CUÁNTICO',
    'shorts.audioTrack': 'Audio Original Cuántico',
    'shorts.prev': 'Anterior Short',
    'shorts.next': 'Siguiente Short',
    'shorts.trending': 'MÁS SHORTS EN TENDENCIA',
    'shorts.none': 'No se encontraron Shorts',

    // Photos Gallery View
    'photos.title': 'GALERÍA DE FOTOS',
    'photos.sub': '& ARTE DIGITAL',
    'photos.desc': 'Fotografía cyberpunk, wallpapers 8K y creaciones visuales de la comunidad',
    'photos.publishBtn': 'Subir Foto / Imagen',
    'photos.searchPlaceholder': 'Buscar fotos e imágenes (ej. Neón, Metrópolis, Maya, Wallpaper, Katana)...',
    'photos.all': '🌟 Todas las Fotos',
    'photos.aiArt': '⚡ Arte con IA (Veo)',
    'photos.neon': '✨ Neón Cuántico',
    'photos.aiBadge': '⚡ IA RENDER',
    'photos.download': 'Descargar Foto',
    'photos.fullscreen': 'Ver en pantalla completa',
    'photos.none': 'No se encontraron fotos o imágenes',
    'photos.by': 'Por',

    // Community Posts View
    'posts.title': 'TEXTO & NOTAS DE VOZ',
    'posts.sub': 'COMUNIDAD',
    'posts.desc': 'Microblogging cuántico, anuncios holográficos y notas de audio en alta fidelidad',
    'posts.publishBtn': 'Publicar Texto o Nota de Voz',
    'posts.searchPlaceholder': 'Buscar textos, notas de voz, anuncios o hashtags (ej. #QuantumAI, #Veo3, #AudioNote)...',
    'posts.playingVoice': 'REPRODUCIENDO NOTA DE VOZ',
    'posts.voiceNote': 'NOTA DE VOZ HOLOGRÁFICA',
    'posts.none': 'No se encontraron publicaciones ni notas de voz',
    'posts.shareTooltip': 'Compartir post',
    'posts.postFallback': 'Post',

    // GIF Hub View
    'gifs.title': 'GIF HUB',
    'gifs.sub': 'BUCLES & ANIMACIONES',
    'gifs.desc': 'GIFs animados cyberpunk, bucles synthwave y stickers holográficos listos para compartir',
    'gifs.publishBtn': 'Publicar GIF Animado',
    'gifs.searchPlaceholder': 'Buscar GIFs animados y bucles (ej. Tunnel, Neon, Matrix, Anime, Drive)...',
    'gifs.all': '👾 Todos los GIFs',
    'gifs.badge': 'GIF BUCLE',
    'gifs.copied': 'Copiado',
    'gifs.copyLink': 'Copiar Enlace',
    'gifs.copyUrl': 'Copiar URL del GIF',
    'gifs.none': 'No se encontraron GIFs',
    'gifs.neonLoops': '✨ Neón & Loops',
    'gifs.memes': '🎭 Memes Cuánticos',
    'gifs.aiNeural': '🧠 IA & Neuronal',

    // 3D Book Mode
    'book.title': 'NAVEGACIÓN 3D',
    'book.sub': 'BOOK-FLIP',
    'book.desc': 'Pasa de página en un entorno 3D holográfico con físicas de perspectiva dimensional.',
    'book.pageOf': 'Página {current} de {total}',
    'book.prev': 'Pág. Anterior',
    'book.next': 'Siguiente Página',
    'book.channel': 'CANAL',
    'book.formatShort': 'FORMATO SHORT 9:16',
    'book.formatWide': 'PANORÁMICO 16:9',
    'book.journalTitle': 'DIARIO CUÁNTICO & ANOTACIONES',
    'book.chapter': 'Capítulo',
    'book.spatialComments': 'Comentarios Anotados por Coordenadas',
    'book.noPins': 'No hay pines aún. Haz clic en el reproductor de la izquierda para fijar uno.',
    'book.neuralTags': 'Etiquetas Neuronales',
    'book.nextPage': 'Próxima Página:',
    'book.flipPage': 'Voltear página',

    // Quad-View
    'quad.title': 'PANEL MULTI-PANTALLA',
    'quad.sub': 'QUAD-VIEW 4X',
    'quad.desc': 'Monitorea, reproduce y captura 4 streams o videos simultáneos con balance acústico independiente.',
    'quad.channelsBadge': '4 CANALES PARALELOS',
    'quad.playAll': 'Reproducir Todos',
    'quad.pauseAll': 'Pausar Todos',
    'quad.muteAll': 'Silenciar Todos',
    'quad.activeAudio': 'Audio Activo: Pantalla #{slot}',
    'quad.mutedAudio': 'Audio Silenciado',
    'quad.screen': 'PANTALLA',
    'quad.soundActive': 'AUDIO ACTIVO',
    'quad.muted': 'SILENCIADO',
    'quad.unmuteTooltip': 'Activar audio en este cuadrante',
    'quad.muteTooltip': 'Silenciar cuadrante',
    'quad.captureTooltip': 'Capturar fotograma de este cuadrante',
    'quad.maximizeTooltip': 'Maximizar cuadrante',
    'quad.restoreTooltip': 'Restaurar cuadrícula 2x2',

    // Omni-Live Studio
    'live.title': 'OMNI-LIVE',
    'live.sub': 'WEBRTC STUDIO',
    'live.desc': 'Transmite en directo con cámara dual, soporte para invitados en el escenario y audio VU-meter.',
    'live.liveBadge': 'EN VIVO',
    'live.enableCam': 'ACTIVAR CÁMARA & MIC',
    'live.startLive': 'TRANSMITIR EN VIVO',
    'live.endLive': 'FINALIZAR LIVE',
    'live.disconnect': 'Desconectar',
    'live.camOffline': 'Cámara Desconectada',
    'live.camOfflineDesc': 'Haz clic en "Activar Cámara & Mic" para iniciar tu transmisión en tiempo real con WebRTC.',
    'live.connectNow': 'Conectar Ahora',
    'live.screenPip': 'PANTALLA',
    'live.viewers': 'espectadores',
    'live.micActive': 'Mic Activo',
    'live.micMuted': 'Mic Silenciado',
    'live.camFront': 'Cámara Frontal',
    'live.camBack': 'Cámara Trasera',
    'live.shareScreen': 'Compartir Pantalla (PiP)',
    'live.stageGuests': 'ESCENARIO MULTI-GUEST (INVITADOS EN VIVO)',
    'live.onStage': 'En el escenario',
    'live.requestingStage': 'Pidiendo subir',
    'live.stepDown': 'Bajar',
    'live.stepOnStage': 'Subir al Escenario',
    'live.chatTitle': 'LIVE CHAT & REGALOS',
    'live.modActive': 'MODERACIÓN IA ACTIVA',
    'live.sendGiftTitle': 'ENVIAR REGALO NEÓN EN VIVO',
    'live.chatPlaceholder': 'Envía un mensaje cuántico...',
    'live.disintegrateTooltip': 'Baneo IA Cuántico (Desintegración)',

    // Direct Messages
    'dms.title': 'MENSAJES DIRECTOS & AUDIO CIFRADO',
    'dms.desc': 'Comunícate con notas de voz cuánticas de alta fidelidad directamente en el navegador.',
    'dms.channelBadge': 'CANAL DE VOZ CIFRADO',
    'dms.recordNote': 'GRABAR NOTA DE VOZ',
    'dms.recording': 'DETENER GRABACIÓN',
    'dms.online': 'Online cuántico',
    'dms.me': 'Yo (Comandante Quantic)',
    'dms.capturing': 'Capturando audio 48kHz...',
    'dms.tapToSpeak': 'Pulsa el botón para enviar audio en vivo',

    // AI Moderation
    'mod.title': 'PANEL DE',
    'mod.titleHighlight': 'MODERACIÓN IA',
    'mod.shield': 'ESCUDO CUÁNTICO ACTIVO',
    'mod.desc': 'Filtra comentarios tóxicos automáticamente con Gemini y gestiona bloqueos con desvanecimiento visual.',
    'mod.bannedWordsTitle': 'FILTRO DE PALABRAS PROHIBIDAS POR IA',
    'mod.addWordPlaceholder': 'Nueva palabra o término tóxico...',
    'mod.add': 'Añadir',
    'mod.testScannerTitle': 'Probar Escáner de Toxicidad en Tiempo Real:',
    'mod.testPlaceholder': 'Escribe una frase para probar el filtro...',
    'mod.analyze': 'Analizar',
    'mod.safeContent': 'Contenido Seguro verificado por IA.',
    'mod.alertPrefix': 'Alerta:',
    'mod.bannedUsersTitle': 'USUARIOS BLOQUEADOS & DESINTEGRACIÓN CUÁNTICA',
    'mod.unban': 'Desbloquear',
    'mod.noBanned': 'No hay usuarios bloqueados en este momento.',

    // Universal Create Media Modal
    'create.title': 'CREAR Y COMPARTIR',
    'create.titleHighlight': 'CONTENIDO',
    'create.subtitle': 'Videos, Shorts, Fotos, Textos, Notas de Voz y GIFs',
    'create.tabVideo': '16:9',
    'create.tabVideoDesc': 'Video Largo',
    'create.tabShort': '9:16',
    'create.tabShortDesc': 'Short',
    'create.tabPhoto': 'Foto',
    'create.tabPhotoDesc': 'Imágenes',
    'create.tabPost': 'Texto',
    'create.tabPostDesc': '& Voz',
    'create.tabGif': 'GIF',
    'create.tabGifDesc': 'Animado',
    'create.videoTitleLabel': 'Título del Video',
    'create.videoTitlePlaceholder': 'Ej. Concierto Holográfico en el Zócalo 2099',
    'create.videoDescLabel': 'Descripción:',
    'create.videoDescPlaceholder': 'Detalles sobre este video cuántico...',
    'create.videoUrlLabel': 'URL del Video (MP4 / WebM):',
    'create.videoThumbLabel': 'URL de Miniatura:',
    'create.videoTagsLabel': 'Etiquetas (separadas por espacio):',
    'create.photoTitleLabel': 'Título de la Foto / Imagen *',
    'create.photoTitlePlaceholder': 'Ej. Rascacielos Neón y Tráfico Holográfico',
    'create.photoUrlLabel': 'URL de la Imagen / Foto *',
    'create.categoryLabel': 'Categoría:',
    'create.postTitleLabel': 'Título del Post (Opcional):',
    'create.postTitlePlaceholder': 'Ej. Anuncio para la comunidad cuántica',
    'create.postContentLabel': 'Mensaje o Contenido de Texto *',
    'create.postContentPlaceholder': '¿Qué estás pensando o creando hoy en QuanticTube?',
    'create.attachVoice': 'Adjuntar Nota de Voz Holográfica',
    'create.voiceReady': 'Audio listo',
    'create.recordingVoice': 'Grabando voz...',
    'create.rerecordVoice': 'Regrabar Nota de Voz',
    'create.recordVoice': 'Grabar Nota de Voz',
    'create.voiceAttachedFormat': '🎵 Formato Cuántico Estéreo adjuntado',
    'create.gifTitleLabel': 'Título del GIF Animado *',
    'create.gifTitlePlaceholder': 'Ej. Bucle Neón Infinito Cyberpunk',
    'create.gifUrlLabel': 'URL del GIF (.gif / Giphy / Tenor) *',
    'create.publishBtn': 'PUBLICAR Y COMPARTIR EN QUANTICTUBE',

    // MexiStudio AI Suite Modal
    'studio.title': 'QuanticStudio IA Suite',
    'studio.subtitle': 'Generador de Video con IA Veo 3.1, Editor Cinematográfico y Sintetizador Musical',
    'studio.tabGenerate': 'Generar con IA (Veo 3.1)',
    'studio.tabEdit': 'Editor & Filtros Neón',
    'studio.tabMusic': 'Sintetizador Musical Lyria',
    'studio.tabUpload': 'Subir / Grabar Cámara',
    'studio.promptLabel': 'Prompt Creativo para Veo 3.1',
    'studio.promptPlaceholder': 'Describe la escena futurista, iluminación de neón, cámaras, personajes...',
    'studio.formatLabel': 'Aspect Ratio / Formato',
    'studio.formatWide': '16:9 Panorámico',
    'studio.formatShort': '9:16 Shorts / Reel',
    'studio.styleLabel': 'Estilo Visual Neuronal',
    'studio.animatePhotoLabel': 'Animar Foto / Imagen a Video (Opcional)',
    'studio.animatePhotoDesc': 'Sube cualquier imagen para animarla automáticamente con paneo de cámara cinemático y partículas neón.',
    'studio.overlayTextLabel': 'Texto o Título Flotante sobre el Video',
    'studio.generatingBtn': 'GENERANDO VIDEO CUÁNTICO...',
    'studio.generateBtn': 'GENERAR VIDEO CON VEO 3.1 & IA',
    'studio.render4k': 'RENDERIZADO 4K',
    'studio.emptyEdit': 'Genera o sube un video primero para ver la previsualización y aplicar filtros.',
    'studio.videoTitle': 'Título del Video',
    'studio.videoTitlePlaceholder': 'Título llamativo para QuanticTube...',
    'studio.videoDesc': 'Descripción / Sinopsis Cuántica',
    'studio.videoDescPlaceholder': 'Descripción generada por IA...',
    'studio.hashtags': 'Hashtags Neuronales',
    'studio.synthTitle': 'SINTETIZADOR PROCEDURAL LYRIA (AUDIO EN TIEMPO REAL)',
    'studio.synthDesc': 'Genera beats futuristas en vivo usando la síntesis analógica de Web Audio API.',
    'studio.stopBeat': 'DETENER BEAT',
    'studio.playBeat': 'ESCUCHAR BEAT EN VIVO',
    'studio.tempo': 'Tempo:',
    'studio.uploadVideo': 'Subir Archivo de Video',
    'studio.uploadVideoDesc': 'Soporta MP4, WebM, MOV en 1080p y 4K',
    'studio.selectFile': 'Seleccionar Archivo',
    'studio.recordWebcam': 'Grabar con Cámara en Vivo',
    'studio.recordWebcamDesc': 'Captura un video directamente desde tu webcam y micrófono',
    'studio.stopRecord': 'Detener Grabación',
    'studio.startRecord': 'Iniciar Grabación',
    'studio.videoReady': 'Video listo para ser publicado',
    'studio.videoNotReady': 'Genera o selecciona un video para continuar',
    'studio.cancel': 'Cancelar',
    'studio.publishToFeed': 'PUBLICAR EN QUANTICTUBE',

    // Creative Director AI Assistant Modal
    'assistant.title': 'DIRECTOR CREATIVO',
    'assistant.titleHighlight': 'QUANTICTUBE IA',
    'assistant.sub': 'IMPULSADO POR GEMINI 3.8 FLASH',
    'assistant.initialGreeting': '¡Saludos creador! Soy el Director Creativo de QuanticTube. ¿Qué video viral con IA Veo 3.1 o estética Cyberpunk vamos a diseñar hoy?',
    'assistant.thinking': 'El Director Creativo está formulando la visión...',
    'assistant.placeholder': 'Pregunta por ideas de guiones, hooks virales, conceptos de video...',
    'assistant.send': 'Enviar',

    // Share Modal
    'share.title': 'COMPARTIR',
    'share.titleHighlight': 'CUÁNTICO',
    'share.tabLink': '🔗 Enlace',
    'share.tabSocial': '🌐 Redes',
    'share.tabQr': '🔳 QR',
    'share.tabEmbed': '💻 Embeber',
    'share.directLinkLabel': 'Enlace Cuántico Directo:',
    'share.copy': 'Copiar',
    'share.copied': '¡Copiado!',
    'share.sendDm': 'Enviar a un amigo en Mensajes Directos (DM)',
    'share.native': 'Abrir menú nativo de compartir en tu dispositivo',
    'share.qrDesc': 'Escanea con la cámara de tu teléfono para abrir directamente este contenido.',
    'share.embedLabel': 'Código HTML para insertar en tu sitio web:',
    'share.copyEmbed': 'Copiar Código Embebido',
    'share.embedCopied': '¡Código HTML Copiado!',
    'share.byAuthor': 'Por',

    // Voice Agent
    'agent.title': 'QUANTUM AI',
    'agent.sub': 'VOZ & MIC EN VIVO',
    'agent.warmMale': 'Quantum AI Live Now',
    'agent.touchToSpeak': 'TOCA PARA HABLAR (MIC DIRECTO)',
    'agent.tapToSend': 'TOCAR PARA ENVIAR VOZ',
    'agent.continuous': 'HABLA CONTINUA',
    'agent.continuousOn': '● EN VIVO ON',
    'agent.micActive': 'MIC ACTIVO',
    'agent.recording': '● GRABANDO',
    'agent.speaking': '🔊 QUANTUM AI HABLANDO...',
    'agent.interrupt': 'Interrumpir',
    'agent.listening': 'Escuchando tu voz... (habla libremente)',
    'agent.processing': 'Quantum AI escuchando y procesando tu voz...',
    'agent.tabChat': 'Platicar',
    'agent.tabTester': 'Probador Mic',
    'agent.tabMemory': 'Agenda',
    'agent.you': 'TÚ',
    'agent.promptHeader': 'Navegación y Consultas del Agente Inteligente:',
    'agent.inputPlaceholder': 'Habla o escribe a Quantum AI...',
    'agent.openFloating': 'Hablar con Quantum AI en Vivo',
    'agent.alarm': 'DESPERTADOR CON VIDEO',
    'agent.alarmDesc': 'Te despertará con tu música favorita.',
    'agent.setFavorite': '🎵 Fijar Video Activo como Favorito',
    'agent.addTask': 'AGREGAR AL MEMORIZANTE',
    'agent.changeName': 'Cambiar Nombre',
    'agent.userRemembered': 'USUARIO RECORDADO',
    'agent.taskTitlePlaceholder': 'Ej: Ver nuevo video de Veo 3.1 o revisar notas...',
    'agent.annotate': 'Anotar',
    'agent.micIntensity': 'Entrada de Voz Micrófono:',
    'agent.capturingVoice': '(Captando Voz)',
    'agent.waitingVoice': '(Silencio/En espera)',
    'agent.uploadVoiceNote': 'SUBIR NOTA DE VOZ',
    'agent.openFullTab': 'ABRIR PESTAÑA FULL',
    'agent.testVoiceBtn': '🎙️ PROBAR VOZ NEURONAL DE ESTUDIO (STUDIO HD)',
    'agent.tasksInMemory': 'TAREAS EN MEMORIA',
    'agent.dateHeader': 'FECHA',
    'agent.noTasks': 'No hay tareas pendientes en el memorizante.',
    'agent.noDate': 'Sin fecha',
    'agent.favoriteVideo': 'Favorito:',

    // Voice Spectrum Tester
    'tester.title': 'PRUEBA FÍSICA: GRABAR & REPRODUCIR TU PROPIA VOZ',
    'tester.recordBtn': 'GRABAR 5 SEGUNDOS DE PRUEBA Y ESCUCHAR MI VOZ',
    'tester.recordingStatus': 'GRABANDO TU VOZ... ({seconds}s)',
    'tester.recordedTitle': '🔊 Tu voz grabada (escúchala con el reproductor):',
    'tester.geminiReplyTitle': '🧠 Respuesta de Quantum AI:',
    'tester.intensityLabel': 'Intensidad de Audio Entrante:',
    'tester.transcriptionLive': '🎙️ Transcripción en Vivo de Prueba:',
    'tester.verified': '¡VERIFICADO!',
    'tester.transcriptionPlaceholder': 'Di algo como: "Hola Quantum AI 1 2 3 probando el micrófono"...',
    'tester.helpTitle': '🚀 ¿Estás usando la vista previa embebida?',
    'tester.helpText': 'Si tu navegador o celular bloquea el micrófono por seguridad dentro del marco, abre la aplicación en una pestaña independiente para autorizar tu micrófono con 1 clic:',
    'tester.helpBtn': 'ABRIR APLICACIÓN EN PESTAÑA COMPLETA',
    'tester.activateBtn': 'ACTIVAR ESPECTRO DE VOZ',
    'tester.restartBtn': 'REINICIAR ESPECTRO',
    'tester.chatBtn': 'PLATICAR CON QUANTUM AI',
    'tester.activeAnalyzer': 'Lector de Frecuencias Activo',
    'tester.idleAnalyzer': 'Lector en Reposo',
    'tester.levelLabel': 'Nivel:',
    'tester.clickBelow': 'Haz clic abajo para iniciar la calibración del micrófono',

    // App & Footer
    'footer.aiConnected': '● Quantum AI Conectado',
    'footer.webrtc': 'WebRTC Dual-Cam',
    'footer.veo': 'Veo 3.1 Rápido',
    'footer.audio': 'Audio Espacial',
    'footer.howToUse': '¿Cómo Usar?',
    'footer.privacy': 'Políticas y Privacidad',
    'footer.aboutUs': 'Sobre Nosotros',
    'footer.allRights': 'Todos los derechos reservados',
    'app.publishFloating': 'Publicar Contenido',

    // Language Toggle
    'lang.es': 'Español',
    'lang.en': 'English'
  },
  en: {
    // Brand & Header
    'brand.subtitle': 'Quantic Social media & videos',
    'search.placeholder': 'Search videos, photos, gifs, text posts...',
    'search.voice': 'AI Voice Search',
    'search.clear': 'Clear',
    'nav.publish': 'PUBLISH',
    'nav.director': 'AI Director',
    'nav.directorFull': 'AI Creative Director',
    'nav.studio': 'STUDIO',
    'nav.channel': 'CHANNEL',
    'nav.channelTooltip': 'Create or manage your channel',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    'nav.myProfile': 'My Profile & Channel',
    'nav.publishMedia': 'Publish Media',
    'nav.signOut': 'Sign Out',
    'nav.publishTooltip': 'Publish and Share (Videos, Shorts, Photos, Text, GIFs)',
    'nav.langSwitch': 'Cambiar a Español',
    'nav.langLabel': 'Language: English',
    'nav.howToUse': 'How to Use',
    'nav.policies': 'Policies',
    'nav.about': 'About Us',

    // Tabs
    'tab.feed': 'Long Videos (16:9)',
    'tab.shorts': 'Shorts (9:16)',
    'tab.photos': 'Photos & Art',
    'tab.posts': 'Community',
    'tab.gifs': 'GIFs Hub',
    'tab.book': '3D Book-Flip',
    'tab.quad': 'Quad-View',
    'tab.live': 'Omni-Live',
    'tab.dms': 'DM Messages',
    'tab.moderation': 'AI Moderation',

    // How to Use Modal
    'help.title': 'INTERACTIVE GUIDE & HOW TO USE',
    'help.subtitle': 'Learn to master all tactile, 3D, physics and AI creator tools',
    'help.clothTitle': '1. Organic 3D Handkerchief Physics (Long Videos & Shorts)',
    'help.clothDesc': 'Our proprietary 3D silk cloth physics allows you to interact with videos like real fabric:',
    'help.flingUp': 'Pull Up = Next Video',
    'help.flingUpDesc': 'Drag the video towards the top edge and release to fling it into the cosmos in 3D, instantly switching to the Next Video.',
    'help.flingDown': 'Pull Down = Previous Video',
    'help.flingDownDesc': 'Drag the video towards the bottom edge to cast it downwards and switch back to the Previous Video.',
    'help.freeRoam': 'Free Roaming & Elastic Bounce',
    'help.freeRoamDesc': 'Wander the video freely across the entire screen. Releasing it in the middle triggers a smooth elastic bounce back to its frame.',
    'help.dragThumbTitle': '2. Drag Miniatures to the Right over the Player',
    'help.dragThumbDesc': 'In the long video playlist, click and drag any thumbnail rightwards over the main player to drop and switch playback seamlessly.',
    'help.authTitle': '3. Subscriptions, Creator Channels & Cloud Publishing',
    'help.authDesc': 'With Google Sign-In & Firebase, create your creator channel in 1 click. Publish 16:9 long videos, 9:16 Shorts, photos, voice notes, and GIFs stored permanently in the cloud.',
    'help.liveTitle': '4K Video Calls & Omni-Live',
    'help.liveDesc': 'Start direct P2P video calls with online users, or broadcast with Omni-Live Dual-Cam and on-stage guests.',
    'help.aiTitle': 'Creative Director & Quantum AI',
    'help.aiDesc': 'Leverage Gemini AI to generate viral video concepts, scripts, Lyria procedural music beats, and Veo 3.1 video animation.',
    'help.gotIt': 'GOT IT!',

    // Policies Modal
    'policies.title': 'PRIVACY POLICIES & TERMS OF SERVICE',
    'policies.subtitle': 'Our commitment to data protection, cloud security and creator rights',
    'policies.sec1Title': '1. Data Protection & Encrypted Cloud Storage',
    'policies.sec1Desc': 'At QuanticTube we protect your personal data with top industry cryptographic standards. Your credentials and auth tokens are handled by Firebase Authentication and Google Cloud Firestore, ensuring zero credential leaks.',
    'policies.sec2Title': '2. Creator Intellectual Property & Zero Data Selling',
    'policies.sec2Desc': 'You retain 100% ownership and copyright of everything you publish (videos, photos, music, podcasts and GIFs). QuanticTube NEVER sells or monetizes your private personal data or browsing history to third-party ad brokers.',
    'policies.sec3Title': '3. AI Automated Moderation & Safe Community',
    'policies.sec3Desc': 'We employ Gemini AI real-time content scanning to eliminate toxicity, harassment, spam, and dangerous content. Toxic comments are vaporized on the spot to protect creators.',
    'policies.sec4Title': '4. Cookies & Local Storage',
    'policies.sec4Desc': 'We use local storage and strictly necessary technical cookies to remember your language preference, audio settings, and active session.',
    'policies.accept': 'ACCEPT AND CONTINUE',

    // About Us Modal
    'about.title': 'ABOUT',
    'about.subtitle': 'The multimedia and social video platform of the future',
    'about.missionTitle': 'Our Mission: Transcending the Limits of Video & Social Media',
    'about.missionDesc': 'QuanticTube was born to revolutionize how the world discovers, creates, and shares media. Bringing together the best of YouTube (16:9 cinema video), TikTok (9:16 interactive vertical shorts), Instagram (high-res photo galleries and digital art), X (microblogging & voice notes), and Twitch (Omni-Live WebRTC studio), powered by organic 3D silk cloth physics and automated AI control.',
    'about.techPillar': 'Quantum Technological Power',
    'about.techDesc': 'Engineered with React 19, TypeScript, GPU 3D acceleration (WebGL/CSS 3D Transforms), low-latency WebRTC, and procedural Web Audio API.',
    'about.aiPillar': 'Gemini 3.8 Artificial Intelligence',
    'about.aiDesc': 'Real-time smart assistant, creative director for scripts, Veo 3.1 video generator, automatic moderation shield, and Lyria music synthesizer.',
    'about.founder': 'Created & Designed by Memo Lopez',
    'about.creatorBadge': 'Founder & Architect',
    'about.founderNote': 'A platform crafted with passion to unite global creators with unprecedented tactile and visual delight.',
    'about.close': 'CLOSE',

    // Long Videos View
    'long.title': 'LONG VIDEOS',
    'long.sub': '16:9 & CINEMA',
    'long.desc': '4K streams, holographic concerts and cinematic productions',
    'long.publishBtn': 'Publish Long Video',
    'long.searchPlaceholder': 'Search Long Videos (e.g. Mariachi, Zocalo, Synthwave, 4K)...',
    'long.tagAll': '🔥 All 16:9',
    'long.tagAi': '⚡ Veo 3.1 AI',
    'long.tagCyber': '🌆 Cyberpunk',
    'long.tagSynth': '🎹 Synthwave',
    'long.playlistTitle': 'LONG VIDEOS PLAYLIST',
    'long.followers': 'quantum followers',
    'long.none': 'No videos selected',

    // Hero Video Player
    'player.views': 'views',
    'player.likes': 'Likes',
    'player.comments': 'Comments',
    'player.share': 'Share',
    'player.draw': 'Draw',
    'player.drawTooltip': 'Live drawing canvas',
    'player.pin': 'Pin Comment',
    'player.pinTooltip': 'Pin spatial comment at X,Y',
    'player.subtitles': 'Subtitles & AI',
    'player.snapshot': '4K Snapshot',
    'player.snapshotTooltip': '4K frame capture',
    'player.clearDrawing': 'Clear strokes',
    'player.pinModalTitle': 'Pin at',
    'player.pinPlaceholder': 'Write your spatial comment...',
    'player.cancel': 'Cancel',
    'player.savePin': 'Save Pin',
    'player.subtitlesTitle': 'AI Subtitles',
    'player.reactionHeart': 'Neon Heart',
    'player.reactionFire': 'Aztec Fire',
    'player.reactionTaco': 'Neon Taco',
    'player.reactionSkull': 'Cyber Skull',
    'player.reactionRose': 'Neon Rose',

    // Shorts View
    'shorts.title': 'SHORT VIDEOS',
    'shorts.sub': '3D SHORTS 9:16',
    'shorts.desc': 'Organic 3D cloth physics, high clarity, vivid colors and spatial audio',
    'shorts.publishBtn': 'Publish 9:16 Short',
    'shorts.searchPlaceholder': 'Search 9:16 Shorts (e.g. Mariachi, AI, Viral, Dance, Beat)...',
    'shorts.badge': 'QUANTUM 3D SHORT',
    'shorts.audioTrack': 'Original Quantum Audio',
    'shorts.prev': 'Previous Short',
    'shorts.next': 'Next Short',
    'shorts.trending': 'MORE TRENDING SHORTS',
    'shorts.none': 'No Shorts found',

    // Photos Gallery View
    'photos.title': 'PHOTOS GALLERY',
    'photos.sub': '& DIGITAL ART',
    'photos.desc': 'Cyberpunk photography, 8K wallpapers and community visual creations',
    'photos.publishBtn': 'Upload Photo / Image',
    'photos.searchPlaceholder': 'Search photos and images (e.g. Neon, Metropolis, Maya, Wallpaper, Katana)...',
    'photos.all': '🌟 All Photos',
    'photos.aiArt': '⚡ AI Art (Veo)',
    'photos.neon': '✨ Quantum Neon',
    'photos.aiBadge': '⚡ AI RENDER',
    'photos.download': 'Download Photo',
    'photos.fullscreen': 'View full screen',
    'photos.none': 'No photos or images found',
    'photos.by': 'By',

    // Community Posts View
    'posts.title': 'TEXT & VOICE NOTES',
    'posts.sub': 'COMMUNITY',
    'posts.desc': 'Quantum microblogging, holographic announcements and hi-fi audio notes',
    'posts.publishBtn': 'Publish Text or Voice Note',
    'posts.searchPlaceholder': 'Search texts, voice notes, news or hashtags (e.g. #QuantumAI, #Veo3, #AudioNote)...',
    'posts.playingVoice': 'PLAYING VOICE NOTE',
    'posts.voiceNote': 'HOLOGRAPHIC VOICE NOTE',
    'posts.none': 'No posts or voice notes found',
    'posts.shareTooltip': 'Share post',
    'posts.postFallback': 'Post',

    // GIF Hub View
    'gifs.title': 'GIF HUB',
    'gifs.sub': 'LOOPS & ANIMATIONS',
    'gifs.desc': 'Cyberpunk animated GIFs, synthwave loops and holographic stickers ready to share',
    'gifs.publishBtn': 'Publish Animated GIF',
    'gifs.searchPlaceholder': 'Search animated GIFs and loops (e.g. Tunnel, Neon, Matrix, Anime, Drive)...',
    'gifs.all': '👾 All GIFs',
    'gifs.badge': 'GIF LOOP',
    'gifs.copied': 'Copied',
    'gifs.copyLink': 'Copy Link',
    'gifs.copyUrl': 'Copy GIF URL',
    'gifs.none': 'No GIFs found',
    'gifs.neonLoops': '✨ Neon & Loops',
    'gifs.memes': '🎭 Quantum Memes',
    'gifs.aiNeural': '🧠 AI & Neural',

    // 3D Book Mode
    'book.title': '3D NAVIGATION',
    'book.sub': 'BOOK-FLIP',
    'book.desc': 'Turn pages in a holographic 3D environment with dimensional perspective physics.',
    'book.pageOf': 'Page {current} of {total}',
    'book.prev': 'Prev. Page',
    'book.next': 'Next Page',
    'book.channel': 'CHANNEL',
    'book.formatShort': 'SHORT 9:16 FORMAT',
    'book.formatWide': 'WIDESCREEN 16:9',
    'book.journalTitle': 'QUANTUM JOURNAL & NOTES',
    'book.chapter': 'Chapter',
    'book.spatialComments': 'Spatial Pinned Comments',
    'book.noPins': 'No pins yet. Click on the left player to pin one.',
    'book.neuralTags': 'Neural Tags',
    'book.nextPage': 'Next Page:',
    'book.flipPage': 'Flip page',

    // Quad-View
    'quad.title': 'MULTI-SCREEN PANEL',
    'quad.sub': 'QUAD-VIEW 4X',
    'quad.desc': 'Watch and play up to 4 quantum live streams simultaneously with focused audio selector.',
    'quad.channelsBadge': '4 PARALLEL CHANNELS',
    'quad.playAll': 'Play All',
    'quad.pauseAll': 'Pause All',
    'quad.muteAll': 'Mute All',
    'quad.activeAudio': 'Active Audio: Screen #{slot}',
    'quad.mutedAudio': 'Audio Muted',
    'quad.screen': 'SCREEN',
    'quad.soundActive': 'AUDIO ACTIVE',
    'quad.muted': 'MUTED',
    'quad.unmuteTooltip': 'Unmute quadrant',
    'quad.muteTooltip': 'Mute quadrant',
    'quad.captureTooltip': 'Capture frame from quadrant',
    'quad.maximizeTooltip': 'Maximize quadrant',
    'quad.restoreTooltip': 'Restore 2x2 grid',

    // Omni-Live Studio
    'live.title': 'OMNI-LIVE',
    'live.sub': 'WEBRTC STUDIO',
    'live.desc': 'Broadcast live with dual-cam, on-stage guests support and audio VU-meter.',
    'live.liveBadge': 'LIVE',
    'live.enableCam': 'ENABLE CAMERA & MIC',
    'live.startLive': 'START LIVE',
    'live.endLive': 'END LIVE',
    'live.disconnect': 'Disconnect',
    'live.camOffline': 'Camera Disconnected',
    'live.camOfflineDesc': 'Click "Enable Camera & Mic" to start your real-time broadcast with WebRTC.',
    'live.connectNow': 'Connect Now',
    'live.screenPip': 'SCREEN',
    'live.viewers': 'viewers',
    'live.micActive': 'Mic Active',
    'live.micMuted': 'Mic Muted',
    'live.camFront': 'Front Camera',
    'live.camBack': 'Rear Camera',
    'live.shareScreen': 'Share Screen (PiP)',
    'live.stageGuests': 'MULTI-GUEST STAGE (LIVE GUESTS)',
    'live.onStage': 'On stage',
    'live.requestingStage': 'Requesting stage',
    'live.stepDown': 'Step Down',
    'live.stepOnStage': 'Step on Stage',
    'live.chatTitle': 'LIVE CHAT & GIFTS',
    'live.modActive': 'AI MODERATION ACTIVE',
    'live.sendGiftTitle': 'SEND LIVE NEON GIFT',
    'live.chatPlaceholder': 'Send a quantum message...',
    'live.disintegrateTooltip': 'Quantum AI Ban (Disintegration)',

    // Direct Messages
    'dms.title': 'DIRECT MESSAGES & ENCRYPTED AUDIO',
    'dms.desc': 'Communicate with high-fidelity quantum voice notes directly inside your browser.',
    'dms.channelBadge': 'ENCRYPTED VOICE CHANNEL',
    'dms.recordNote': 'RECORD VOICE NOTE',
    'dms.recording': 'STOP RECORDING',
    'dms.online': 'Quantum Online',
    'dms.me': 'Me (Commander Quantic)',
    'dms.capturing': 'Capturing 48kHz audio...',
    'dms.tapToSpeak': 'Press the button to send live audio',

    // AI Moderation
    'mod.title': 'AI',
    'mod.titleHighlight': 'MODERATION PANEL',
    'mod.shield': 'QUANTUM SHIELD ACTIVE',
    'mod.desc': 'Filter toxic comments automatically with Gemini and manage bans with visual matrix disintegration.',
    'mod.bannedWordsTitle': 'AI BANNED WORDS FILTER',
    'mod.addWordPlaceholder': 'New word or toxic term...',
    'mod.add': 'Add',
    'mod.testScannerTitle': 'Test Real-Time Toxicity Scanner:',
    'mod.testPlaceholder': 'Type a phrase to test the filter...',
    'mod.analyze': 'Analyze',
    'mod.safeContent': 'Safe Content verified by AI.',
    'mod.alertPrefix': 'Alert:',
    'mod.bannedUsersTitle': 'BANNED USERS & QUANTUM DISINTEGRATION',
    'mod.unban': 'Unban',
    'mod.noBanned': 'No banned users at this moment.',

    // Universal Create Media Modal
    'create.title': 'CREATE & SHARE',
    'create.titleHighlight': 'CONTENT',
    'create.subtitle': 'Videos, Shorts, Photos, Text, Voice Notes and GIFs',
    'create.tabVideo': '16:9',
    'create.tabVideoDesc': 'Long Video',
    'create.tabShort': '9:16',
    'create.tabShortDesc': 'Short',
    'create.tabPhoto': 'Photo',
    'create.tabPhotoDesc': 'Images',
    'create.tabPost': 'Text',
    'create.tabPostDesc': '& Voice',
    'create.tabGif': 'GIF',
    'create.tabGifDesc': 'Animated',
    'create.videoTitleLabel': 'Video Title',
    'create.videoTitlePlaceholder': 'E.g. Holographic Concert at Neon Square 2099',
    'create.videoDescLabel': 'Description:',
    'create.videoDescPlaceholder': 'Details about this quantum video...',
    'create.videoUrlLabel': 'Video URL (MP4 / WebM):',
    'create.videoThumbLabel': 'Thumbnail URL:',
    'create.videoTagsLabel': 'Tags (separated by space):',
    'create.photoTitleLabel': 'Photo / Image Title *',
    'create.photoTitlePlaceholder': 'E.g. Neon Skyscraper & Holographic Traffic',
    'create.photoUrlLabel': 'Image / Photo URL *',
    'create.categoryLabel': 'Category:',
    'create.postTitleLabel': 'Post Title (Optional):',
    'create.postTitlePlaceholder': 'E.g. Announcement for the quantum community',
    'create.postContentLabel': 'Message or Text Content *',
    'create.postContentPlaceholder': 'What are you thinking or creating today on QuanticTube?',
    'create.attachVoice': 'Attach Holographic Voice Note',
    'create.voiceReady': 'Audio ready',
    'create.recordingVoice': 'Recording voice...',
    'create.rerecordVoice': 'Rerecord Voice Note',
    'create.recordVoice': 'Record Voice Note',
    'create.voiceAttachedFormat': '🎵 Quantum Stereo Format attached',
    'create.gifTitleLabel': 'Animated GIF Title *',
    'create.gifTitlePlaceholder': 'E.g. Cyberpunk Infinite Neon Loop',
    'create.gifUrlLabel': 'GIF URL (.gif / Giphy / Tenor) *',
    'create.publishBtn': 'PUBLISH & SHARE ON QUANTICTUBE',

    // MexiStudio AI Suite Modal
    'studio.title': 'QuanticStudio AI Suite',
    'studio.subtitle': 'Veo 3.1 AI Video Generator, Cinematic Editor and Lyria Music Synthesizer',
    'studio.tabGenerate': 'Generate with AI (Veo 3.1)',
    'studio.tabEdit': 'Editor & Neon Filters',
    'studio.tabMusic': 'Lyria Music Synthesizer',
    'studio.tabUpload': 'Upload / Record Camera',
    'studio.promptLabel': 'Creative Prompt for Veo 3.1',
    'studio.promptPlaceholder': 'Describe futuristic scene, neon lighting, cameras, characters...',
    'studio.formatLabel': 'Aspect Ratio / Format',
    'studio.formatWide': '16:9 Widescreen',
    'studio.formatShort': '9:16 Shorts / Reel',
    'studio.styleLabel': 'Neural Visual Style',
    'studio.animatePhotoLabel': 'Animate Photo / Image to Video (Optional)',
    'studio.animatePhotoDesc': 'Upload any image to animate it automatically with cinematic camera pan and neon particles.',
    'studio.overlayTextLabel': 'Overlay Title Floating on Video',
    'studio.generatingBtn': 'GENERATING QUANTUM VIDEO...',
    'studio.generateBtn': 'GENERATE VIDEO WITH VEO 3.1 & AI',
    'studio.render4k': '4K RENDER',
    'studio.emptyEdit': 'Generate or upload a video first to see preview and apply filters.',
    'studio.videoTitle': 'Video Title',
    'studio.videoTitlePlaceholder': 'Catchy title for QuanticTube...',
    'studio.videoDesc': 'Quantum Description / Synopsis',
    'studio.videoDescPlaceholder': 'AI generated description...',
    'studio.hashtags': 'Neural Hashtags',
    'studio.synthTitle': 'PROCEDURAL LYRIA SYNTH (REAL-TIME AUDIO)',
    'studio.synthDesc': 'Generate futuristic beats live using Web Audio API analog synthesis.',
    'studio.stopBeat': 'STOP BEAT',
    'studio.playBeat': 'PLAY LIVE BEAT',
    'studio.tempo': 'Tempo:',
    'studio.uploadVideo': 'Upload Video File',
    'studio.uploadVideoDesc': 'Supports MP4, WebM, MOV in 1080p and 4K',
    'studio.selectFile': 'Select File',
    'studio.recordWebcam': 'Record with Live Camera',
    'studio.recordWebcamDesc': 'Capture video directly from your webcam and microphone',
    'studio.stopRecord': 'Stop Recording',
    'studio.startRecord': 'Start Recording',
    'studio.videoReady': 'Video ready to be published',
    'studio.videoNotReady': 'Generate or select a video to continue',
    'studio.cancel': 'Cancel',
    'studio.publishToFeed': 'PUBLISH ON QUANTICTUBE',

    // Creative Director AI Assistant Modal
    'assistant.title': 'CREATIVE DIRECTOR',
    'assistant.titleHighlight': 'QUANTICTUBE AI',
    'assistant.sub': 'POWERED BY GEMINI 3.8 FLASH',
    'assistant.initialGreeting': 'Greetings creator! I am the QuanticTube Creative Director. What viral video with Veo 3.1 AI or Cyberpunk aesthetics are we designing today?',
    'assistant.thinking': 'The Creative Director is formulating the vision...',
    'assistant.placeholder': 'Ask for script ideas, viral hooks, video concepts...',
    'assistant.send': 'Send',

    // Share Modal
    'share.title': 'SHARE',
    'share.titleHighlight': 'QUANTUM',
    'share.tabLink': '🔗 Link',
    'share.tabSocial': '🌐 Social',
    'share.tabQr': '🔳 QR',
    'share.tabEmbed': '💻 Embed',
    'share.directLinkLabel': 'Direct Quantum Link:',
    'share.copy': 'Copy',
    'share.copied': 'Copied!',
    'share.sendDm': 'Send to a friend in Direct Messages (DM)',
    'share.native': 'Open native share menu on your device',
    'share.qrDesc': 'Scan with your phone camera to directly open this content.',
    'share.embedLabel': 'HTML code to embed on your website:',
    'share.copyEmbed': 'Copy Embed Code',
    'share.embedCopied': 'HTML Embed Code Copied!',
    'share.byAuthor': 'By',

    // Voice Agent
    'agent.title': 'QUANTUM AI',
    'agent.sub': 'VOICE & LIVE MIC',
    'agent.warmMale': 'Quantum AI Live Now',
    'agent.touchToSpeak': 'TAP TO SPEAK (DIRECT MIC)',
    'agent.tapToSend': 'TAP TO SEND VOICE',
    'agent.continuous': 'CONTINUOUS TALK',
    'agent.continuousOn': '● LIVE TALK ON',
    'agent.micActive': 'MIC ACTIVE',
    'agent.recording': '● RECORDING',
    'agent.speaking': '🔊 QUANTUM AI SPEAKING...',
    'agent.interrupt': 'Interrupt',
    'agent.listening': 'Listening to your voice... (speak freely)',
    'agent.processing': 'Quantum AI listening and processing your voice...',
    'agent.tabChat': 'Chat',
    'agent.tabTester': 'Mic Tester',
    'agent.tabMemory': 'Agenda',
    'agent.you': 'YOU',
    'agent.promptHeader': 'Smart Navigation & Agent Actions:',
    'agent.inputPlaceholder': 'Speak or type to Quantum AI...',
    'agent.openFloating': 'Talk with Quantum AI Live',
    'agent.alarm': 'VIDEO ALARM CLOCK',
    'agent.alarmDesc': 'Wakes you up with your favorite music.',
    'agent.setFavorite': '🎵 Set Active Video as Favorite',
    'agent.addTask': 'ADD TO MEMORY NOTEBOOK',
    'agent.changeName': 'Change Name',
    'agent.userRemembered': 'REMEMBERED USER',
    'agent.taskTitlePlaceholder': 'E.g. Watch new Veo 3.1 video or check notes...',
    'agent.annotate': 'Save Task',
    'agent.micIntensity': 'Microphone Voice Input:',
    'agent.capturingVoice': '(Capturing Voice)',
    'agent.waitingVoice': '(Silence/Waiting)',
    'agent.uploadVoiceNote': 'UPLOAD VOICE NOTE',
    'agent.openFullTab': 'OPEN FULL TAB',
    'agent.testVoiceBtn': '🎙️ TEST STUDIO NEURAL VOICE (STUDIO HD)',
    'agent.tasksInMemory': 'TASKS IN MEMORY',
    'agent.dateHeader': 'DATE',
    'agent.noTasks': 'No pending tasks in memory notebook.',
    'agent.noDate': 'No date',
    'agent.favoriteVideo': 'Favorite:',

    // Voice Spectrum Tester
    'tester.title': 'PHYSICAL TEST: RECORD & PLAYBACK YOUR OWN VOICE',
    'tester.recordBtn': 'RECORD 5 SECONDS TEST & HEAR MY VOICE',
    'tester.recordingStatus': 'RECORDING YOUR VOICE... ({seconds}s)',
    'tester.recordedTitle': '🔊 Your recorded voice (listen with the player):',
    'tester.geminiReplyTitle': '🧠 Quantum AI Response:',
    'tester.intensityLabel': 'Incoming Audio Intensity:',
    'tester.transcriptionLive': '🎙️ Test Live Transcription:',
    'tester.verified': 'VERIFIED!',
    'tester.transcriptionPlaceholder': 'Say something like: "Hello Quantum AI 1 2 3 testing microphone"...',
    'tester.helpTitle': '🚀 Are you using the embedded preview?',
    'tester.helpText': 'If your browser blocks the microphone inside this iframe, open the app in a standalone tab to grant mic permission in 1 click:',
    'tester.helpBtn': 'OPEN APP IN FULL STANDALONE TAB',
    'tester.activateBtn': 'ACTIVATE VOICE SPECTRUM',
    'tester.restartBtn': 'RESTART SPECTRUM',
    'tester.chatBtn': 'CHAT WITH QUANTUM AI',
    'tester.activeAnalyzer': 'Frequency Analyzer Active',
    'tester.idleAnalyzer': 'Analyzer Idle',
    'tester.levelLabel': 'Level:',
    'tester.clickBelow': 'Click below to start microphone calibration',

    // App & Footer
    'footer.aiConnected': '● Quantum AI Connected',
    'footer.webrtc': 'WebRTC Dual-Cam',
    'footer.veo': 'Veo 3.1 Fast',
    'footer.audio': 'Spatial Audio',
    'footer.howToUse': 'How to Use',
    'footer.privacy': 'Policies & Privacy',
    'footer.aboutUs': 'About Us',
    'footer.allRights': 'All rights reserved',
    'app.publishFloating': 'Publish Content',

    // Language Toggle
    'lang.es': 'Español',
    'lang.en': 'English'
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'es',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key: string, fallback?: string) => fallback || key
});

const STORAGE_KEY = 'quantictube_language_pref';

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      try {
        const saved = localStorage.getItem(STORAGE_KEY) as Language;
        if (saved === 'es' || saved === 'en') return saved;
      } catch (e) {}
    }
    return 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem(STORAGE_KEY, lang);
      } catch (e) {}
    }
  };

  const toggleLanguage = () => {
    setLanguage(language === 'es' ? 'en' : 'es');
  };

  const t = (key: string, fallback?: string): string => {
    return translations[language]?.[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
